image: registry.gitlab.com/gitlab-org/gitlab-build-images:golang-1.10-git-2.17

before_script:
  - go get -u github.com/kardianos/govendor

build:
  only:
    - tags
  script:
    - mkdir -p /go/src/github.com/ahmadsherif
    - cp -r /builds/ahmadsherif/imap-mailbox-exporter /go/src/github.com/ahmadsherif
    - cd /go/src/github.com/ahmadsherif/imap-mailbox-exporter
    - govendor build
    - mkdir -p /builds/ahmadsherif/imap-mailbox-exporter/bin
    - cp imap-mailbox-exporter /builds/ahmadsherif/imap-mailbox-exporter/bin/
  artifacts:
    paths:
      - /builds/ahmadsherif/imap-mailbox-exporter/bin/
    name: binary-go1.10
    expire_in: 2 years

